# Testing FastAPI endpoints



### --------------------------------------------------------------------------------------------------------------------
# Base URL Local
@baseUrl = http://127.0.0.1:8000



### Home url -----------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/
Accept: application/json



### Create a new todo --------------------------------------------------------------------------------------------------
POST {{baseUrl}}/todos/
Content-Type: application/json

{
  "title": "Buy milk",
  "priority": 2
}



### Get all todos as a list --------------------------------------------------------------------------------------------
GET {{baseUrl}}/todos/
Accept: application/json



### Update a todo using id ---------------------------------------------------------------------------------------------
PUT {{baseUrl}}/todos/1
Content-Type: application/json

{
  "title": "Buy milk and bread",
  "priority": 3,
  "completed": true
}



### Delete a todo using id ---------------------------------------------------------------------------------------------
DELETE {{baseUrl}}/todos/1
Content-Type: application/json



### --------------------------------------------------------------------------------------------------------------------
